name = "heaven-receipt"
compatibility_date = "2024-01-07"

[pages]
build-command = "next build && rm -rf out && mkdir -p out/.next && cp -r .next/standalone/. out && cp -r .next/static out/.next && cp -r public out"
build-output-dir = "out"
